# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 13:36
from __future__ import unicode_literals

import cecbr_photos.photos.facemodels
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cover_url', models.URLField()),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('processed', models.BooleanField(default=False)),
                ('analyzed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['season', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('small_url', models.URLField()),
                ('large_url', models.URLField()),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='photo_directory_path_s', verbose_name='Small Image')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='photo_directory_path_l', verbose_name='Large Image')),
                ('json_data', models.TextField(blank=True, null=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('found', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['album', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=4, verbose_name='Season Name')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_svm', models.FilePathField(blank=True, match='*.pkl', null=True, verbose_name='/home/trainers/svm')),
                ('trained_gcc', models.FilePathField(blank=True, match='*.pkl', null=True, verbose_name='/home/trainers/gcc')),
                ('trained', models.BooleanField(default=False)),
                ('trained_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=cecbr_photos.photos.models.training_directory_path)),
                ('json_data', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campuser',
            name='cecbr_pwd',
            field=models.CharField(help_text='Please enter your CECBR Password...', max_length=128, verbose_name='CECBR Password'),
        ),
        migrations.AlterField(
            model_name='campuser',
            name='cecbr_uname',
            field=models.CharField(help_text='Please enter your CECBR User Name...', max_length=128, verbose_name='CECBR User Name'),
        ),
        migrations.AddField(
            model_name='trainingphoto',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.CampUser'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='campuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.CampUser'),
        ),
        migrations.AddField(
            model_name='traininggroup',
            name='people',
            field=models.ManyToManyField(to='photos.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='campuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.CampUser'),
        ),
        migrations.AddField(
            model_name='person',
            name='photos',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Season'),
        ),
    ]
