# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20170809_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='analyzed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campuser',
            name='last_album_view',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
